#!/usr/bin/env bash

set -euox pipefail

logprefix="Trace-Analyzer:"

echo "$logprefix setting up directory structure."

mkdir -p outputs/

pushd outputs

# required by the CLI
mkdir -p data/

for tracefilepath in "$@"
do
    echo "$logprefix running AntTracks Analyzer on $tracefilepath."

    java -jar /workdir/CLI.jar "$tracefilepath"
done

echo "$logprefix running analysis script"

/workdir/analyzer/run.sh "data/lifetimes.csv"

popd
